AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to provision an ECS cluster with blue/green deployment.

Parameters:
  EnvironmentName:
    Description: The name of the environment (e.g., dev, prod)
    Type: String
    Default: dev

  VPCId:
    Description: ID of the VPC
    Type: AWS::EC2::VPC::Id

  PublicSubnet1Id:
    Description: ID of Public Subnet 1
    Type: AWS::EC2::Subnet::Id

  PublicSubnet2Id:
    Description: ID of Public Subnet 2
    Type: AWS::EC2::Subnet::Id

  AppSecurityGroupId:
    Description: ID of the Application Security Group
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${EnvironmentName}-ecs-cluster"

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${EnvironmentName}-task"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: "256"
      Memory: "512"
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: app-container
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EnvironmentName}-app:latest"
          PortMappings:
            - ContainerPort: 80

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AmazonECSTaskExecutionRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 2
      LaunchType: FARGATE
      DeploymentController:
        Type: CODE_DEPLOY
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref AppSecurityGroupId
          Subnets:
            - !Ref PublicSubnet1Id
            - !Ref PublicSubnet2Id
      TaskDefinition: !Ref TaskDefinition

Outputs:
  ECSClusterName:
    Description: Name of the ECS Cluster
    Value: !Ref ECSCluster

  TaskDefinitionArn:
    Description: ARN of the Task Definition
    Value: !Ref TaskDefinition